/** Vocabulary is intentionally disjoint so an identifier's kind can be recognized without context. */
export const CONVERSATION_ID_ADJECTIVES = [
  "airy", "amber", "ancient", "awkward", "azure", "balmy", "bold", "bouncy", "brave", "breezy",
  "bright", "brisk", "bubbly", "bucolic", "caffeinated", "calm", "candid", "cheerful", "chill", "clear",
  "clever", "cloudy", "coastal", "cool", "cosmic", "cozy", "crafty", "crazy", "crisp", "curious",
  "dainty", "dappled", "daring", "dashing", "dejected", "devoted", "distant", "dramatic", "dreamy", "eager",
  "electric", "enchanted", "epic", "even", "fae", "fiery", "fleet", "floaty", "fluffy", "fresh",
  "friendly", "frosty", "funny", "fuzzy", "gentle", "giant", "gleaming", "glowing", "golden", "goofy",
  "graceful", "groovy", "happy", "hardy", "hidden", "hollow", "hushed", "icy", "impish", "ivory",
  "jaunty", "jazzy", "jolly", "keen", "kind", "leafy", "lively", "local", "lucid", "lucky",
  "lunar", "magical", "mellow", "merry", "misty", "modest", "moonlit", "mossy", "musical", "nimble",
  "noble", "oceanic", "peaceful", "peachy", "perky", "playful", "plucky", "polished", "quiet", "quirky",
  "radiant", "rapid", "rosy", "rustic", "sage", "serene", "sharp", "silent", "silver", "sleepy",
  "smooth", "snappy", "snowy", "solar", "sparkly", "spiffy", "spry", "steady", "stellar", "stringy",
  "sunny", "sweet", "swift", "tedious", "tender", "tiny", "tranquil", "twinkly", "upbeat", "velvety",
  "vivid", "warm", "watchful", "wavy", "wild", "wise", "witty", "wonky", "zany", "zesty",
  "zingy",
] as const;

export const CONVERSATION_ID_NOUNS = [
  "acorn", "alpaca", "antelope", "aster", "axolotl", "badger", "beaver", "beetle", "birch", "bison",
  "blob", "blossom", "bluebird", "bobcat", "bonsai", "breeze", "brook", "bubble", "bunny", "canyon",
  "capybara", "cardinal", "cedar", "cherry", "chime", "cloud", "clover", "comet", "coral", "coyote",
  "crane", "creek", "cricket", "dahlia", "dandelion", "dewdrop", "dolphin", "dragon", "duck", "dusk",
  "eagle", "echo", "elf", "ember", "faerie", "falcon", "fern", "finch", "firefly", "forest",
  "fox", "galaxy", "garden", "gecko", "geode", "glacier", "gnome", "gong", "goose", "grove",
  "harbor", "hawk", "hedgehog", "herb", "heron", "hill", "hummingbird", "iris", "island", "jay",
  "jellyfish", "juniper", "kestrel", "kitten", "kiwi", "koala", "koan", "koi", "kumquat", "lagoon",
  "lake", "lantern", "lark", "lemur", "lion", "lotus", "mandala", "mango", "mantra", "maple",
  "marigold", "marmot", "meadow", "mesa", "mitten", "mochi", "moonbeam", "mountain", "mouse", "mushroom",
  "narwhal", "nebula", "newt", "oak", "orchid", "origami", "osprey", "otter", "owl", "panda",
  "pebble", "penguin", "pine", "pixie", "planet", "plume", "pond", "poppy", "prairie", "puffin",
  "quartz", "quokka", "rabbit", "raccoon", "raven", "reef", "river", "robin", "rocket", "salmon",
  "sequoia", "shell", "shore", "sloth", "sparrow", "sprite", "star", "stardust", "stick", "stone",
  "storm", "stream", "summit", "swan", "teacup", "thunder", "toadstool", "turtle", "willow", "wisp",
  "wombat", "zafu", "zephyr",
] as const;

export const RUN_ID_VERBS = [
  "adapt", "align", "analyze", "apply", "assemble", "assess", "audit", "authorize", "automate", "balance",
  "benchmark", "bootstrap", "branch", "breathe", "browse", "brush", "build", "bundle", "cache", "calculate",
  "calibrate", "capture", "catalog", "center", "chant", "chart", "check", "chew", "classify", "clone",
  "cluster", "collect", "combine", "compare", "compile", "complete", "compose", "compress", "compute", "configure",
  "confirm", "connect", "consider", "consolidate", "construct", "contrast", "convert", "coordinate", "correlate", "crawl",
  "create", "cry", "cuddle", "customize", "daydream", "debug", "decode", "deduce", "deliver", "deploy",
  "design", "diagnose", "diagram", "diff", "discover", "dispatch", "distill", "distribute", "document", "doodle",
  "draft", "drift", "edit", "energize", "engineer", "enumerate", "estimate", "evaluate", "execute", "exhale",
  "expand", "explore", "export", "extract", "filter", "finish", "fix", "float", "flow", "format",
  "frolic", "gather", "generate", "grep", "guide", "hum", "identify", "imagine", "implement", "import",
  "improve", "index", "infer", "inhale", "initialize", "inspect", "integrate", "investigate", "isolate", "iterate",
  "join", "launch", "levitate", "link", "lint", "load", "locate", "log", "map", "match",
  "meander", "measure", "meditate", "merge", "migrate", "model", "monitor", "muse", "navigate", "optimize",
  "orchestrate", "organize", "package", "parse", "patch", "pinpoint", "plan", "poke", "polish", "ponder",
  "pounce", "predict", "prepare", "prioritize", "process", "prototype", "publish", "query", "rank", "reconcile",
  "record", "recover", "reduce", "refactor", "refine", "reload", "render", "repair", "resolve", "restructure",
  "retrieve", "review", "revise", "route", "run", "sample", "scan", "schedule", "script", "scrub",
  "search", "select", "sequence", "ship", "shout", "simplify", "simulate", "slice", "solve", "sort",
  "sparkle", "split", "stage", "streamline", "summarize", "swim", "sync", "synthesize", "tally", "target",
  "test", "think", "tokenize", "trace", "track", "train", "transform", "translate", "troubleshoot", "tune",
  "twirl", "update", "upgrade", "validate", "verify", "wander", "whimper", "whine", "whisper", "work",
  "write", "yield", "yodel", "zip", "zoom",
] as const;

export const RUN_ID_ADVERBS = [
  "ably", "abruptly", "accurately", "actively", "adaptively", "agilely", "analytically", "aptly", "audibly", "automatically",
  "bigly", "blissfully", "boastfully", "boldly", "breezily", "brightly", "briskly", "buoyantly", "calmly", "carefully",
  "cautiously", "certainly", "cleanly", "clearly", "closely", "coherently", "collaboratively", "concisely", "concurrently", "confidently",
  "conservatively", "consistently", "constructively", "continuously", "correctly", "coyly", "creatively", "crisply", "critically", "cutely",
  "deeply", "defiantly", "deftly", "deliberately", "dependably", "deterministically", "diligently", "directly", "dutifully", "dynamically",
  "easily", "efficiently", "elegantly", "ethereally", "evenly", "exactly", "expertly", "explicitly", "faithfully", "fancifully",
  "firmly", "flawlessly", "flexibly", "fluently", "freely", "freshly", "fully", "gently", "gingerly", "gladly",
  "gleefully", "gracefully", "gradually", "greedily", "haltingly", "hastily", "helpfully", "honestly", "hurriedly", "immediately",
  "incrementally", "independently", "intelligently", "intentionally", "intuitively", "irritably", "iteratively", "keenly", "lazily", "lightly",
  "locally", "logically", "loosely", "madly", "manually", "methodically", "meticulously", "mindfully", "minimally", "modularly",
  "morosely", "natively", "naturally", "neatly", "noisily", "obediently", "objectively", "observantly", "openly", "optimally",
  "orderly", "patiently", "placidly", "plainly", "practically", "precisely", "predictably", "proactively", "productively", "progressively",
  "promptly", "properly", "purposefully", "quickly", "rapidly", "readily", "recursively", "reliably", "repeatedly", "responsively",
  "restfully", "rigorously", "robustly", "routinely", "rudely", "safely", "seamlessly", "secretly", "securely", "separately",
  "sharply", "silently", "simply", "skillfully", "slowly", "slyly", "smartly", "smoothly", "snappily", "sneakily",
  "softly", "solidly", "soundly", "speedily", "squarely", "stably", "steadily", "strategically", "strictly", "strongly",
  "successfully", "succinctly", "surely", "systematically", "tactically", "technically", "tersely", "thoroughly", "thoughtfully", "tightly",
  "tirelessly", "transparently", "truly", "uniformly", "usefully", "visibly", "vivaciously", "warmly", "weakly", "wearily",
  "whimsically", "widely", "willingly", "wisely", "wistfully", "yearly",
] as const;
